fix: remove Material errors
gliff-ai/annotate pull request #54
Opened 2021-03-23 18:16 UTC by cooper667

![image](https://user-images.githubusercontent.com/3502798/112197225-c0100d00-8c03-11eb-98d0-e4097ce297c2.png)

This is caused by IconButtons being used in a ButtonGroup which is invalid as noted [here](https://github.com/mui-org/material-ui/issues/16156#issuecomment-500853073)

This removes then and just wraps in a div.

I'll add in proper styling when we start with a style sheet etc

2021-03-23 19:48 UTC, ChasNelson1990 commented
Actually, I think it makes more sense to do the opposite here - use a normal button but the icon component, as per the example they show rather than using divs unnecessarily - the whole point of the button group component is it changes the styling of the buttons within in in a way that I don't think we should be replicating.

2021-03-23 19:49 UTC, ChasNelson1990 requested changes
Actually, I think it makes more sense to do the opposite here - use a normal button but the icon component, as per the example they show rather than using divs unnecessarily - the whole point of the button group component is it changes the styling of the buttons within in in a way that I don't think we should be replicating.

2021-03-25 12:49 UTC, ChasNelson1990 approved these changes

2021-03-25 12:52 UTC, SilviaZeta approved these changes

2021-03-25 13:01 UTC, merged