feat: Compare annotations
gliff-ai/annotate pull request #768
Opened 2022-06-20 18:22 UTC by philipjackson

## Description

Passing `annotationsObject2` to ANNOTATE along with `readonly` now causes it to render the two annotations side by side, along with a diff overlay on the right hand pane, like in Percy. Also:

- Displays a diff toolbar in the bottom-right, allowing to toggle between single view and side-by-side view, and toggle the diff overlay
- Adds a second autocomplete to the Users popover, allowing you to choose any two annotations for comparison (the `annotationsObject` and `annotationsObject2` props just tell ANNOTATE which annotations to show first, with `annotationsObject2` having the dual role of telling it to operate in comparison mode - all annotations should also be passed in the `userAnnotations` prop whenever readonly is set, which has a `{ [username: string]: Annotations }` structure mapping usernames to annotationObjects for that image.
- LayersPopover now lists layers from either `annotationsObject` or `annotationsObject2`, with a toggle to switch between them

## Checklist:

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!

- [ ] I have read the gliff.ai Contribution Guide.
- [ ] I have requested to **pull a branch** and not from main.
- [ ] I have checked all commit message styles match the requested structure.
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned **3 or less** reviewers.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.
- [ ] If appropriate, I have bumped any version numbers.

2022-06-21 12:43 UTC, joshuajames-smith requested changes
- [x] `Select A User` dialogue > Can you label each select field to "User 1" and "User 2"? This will improve the UX by providing helpful feedback.
- [x] Could you rename the tooltip from "Single view" to "Single View".
- [ ] Could you rename the tooltip from "Side-by-side view" to "Side-by-Side View".
- [ ] Could you rename the tooltip from "Show diff" to "Show Difference".
- [ ] On Safari, when you toggle the difference off and then on the red difference does not show unless the minimap is opened or interacted with.
- [ ] Could we remove the `Background Settings` secondary tool bar from remaining open? It currently will not disappear once open.
- [ ] The original design adds a dividing line so when a user zooms in there a clear operation between the two sides - see below.
- [ ] Could we also add names to the images so the user has constant feedback to which image and annotations belong to which user - see below.

<img width="600" alt="Intended Design" src="https://user-images.githubusercontent.com/83074763/155736306-6b7e3f8b-53c4-436a-9588-a2c5201185a9.png">

<img width="600" alt="Current Design" src="https://user-images.githubusercontent.com/83074763/174799158-a3c7889d-a184-4cb7-bd39-b8a78e95c646.png">

2022-06-22 10:05 UTC, joshuajames-smith requested changes
- [x] The name tags on each image. Can we change the CSS to "font-weight: regular; border-radius: 8px; border-colour: #F2F2F2;"?
- [x] The `background settings` secondary toolbox remains open. I feel in this instance it is likely to get in the way as there are no other secondary toolboxs a user can access. Could we disable the ability for the secondary toolbox to remain open if a user clicks away?
- [ ] The divider line between the 2 images. Can we change the CSS to "border-right-widht: 2px;" and "border-left-width: 2px;" respectively?
- [ ] The issue is still persisting with Safari not rendering the difference when toggled off and then on again. It only appears if the minimap is interacted with or an annotation is selected.

2022-06-24 10:17 UTC, joshuajames-smith approved these changes

2022-06-28 08:18 UTC, cooper667 reviewed
No snapshots?

2022-07-12 13:02 UTC, SilviaZeta submitted a review, later dismissed

2022-07-13 13:33 UTC, SilviaZeta approved these changes

2022-07-13 13:48 UTC, ChasNelson1990 approved these changes

2022-07-13 13:49 UTC, merged