feat!: User feedback
gliff-ai/annotate pull request #775
Opened 2022-07-21 08:46 UTC by SilviaZeta

## Description
- add a card component for collecting user feedback when annotations are saved.

relates to gliff-ai/annotate/issues/774
relies on gliff-ai/style#256

## Checklist:

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!

- [ ] I have read the gliff.ai Contribution Guide.
- [ ] I have requested to **pull a branch** and not from main.
- [ ] I have checked all commit message styles match the requested structure.
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned **3 or less** reviewers.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.
- [ ] If appropriate, I have bumped any version numbers.

2022-07-25 16:19 UTC, joshuajames-smith requested changes
![feedback-form](https://user-images.githubusercontent.com/83074763/180825753-c7c5cbc6-f3f7-4fec-982c-ab4e6a6a3532.png)

---

I have some thoughts about enhancing the UI design to further improve the UX and design consistency of this new feature. These are shown in the above design.

- [x] Widen the dialogue as this will allow for increased space for text input.
- [ ] Change the dialogue heading.
- [ ] Change the dialogue copy and left align.
- [ ] Edit the star rating to include new copy and change star colour. Possibly add custom star icon with MaterialUI as basis? - this is ready and I can add to STYLE when needed.
- [ ] Change the copy of the text field prompt.
- [ ] Add dividers between the two sections of the dialogue.
- [ ] Change the copy of the buttons.

2022-07-26 14:47 UTC, ChasNelson1990 approved these changes, later dismissed

2022-07-26 14:51 UTC, joshuajames-smith requested changes
<img width="563" alt="Screenshot 2022-07-26 at 15 49 05" src="https://user-images.githubusercontent.com/83074763/181038511-5d8b81da-679a-4ee2-b4eb-48a14fd8ce3d.png">

One final change otherwise it looks good to go! Can we reduce the top margin/padding of the dialogue between the text and topbar?

2022-07-26 15:33 UTC, ChasNelson1990 submitted a review, later dismissed

2022-07-26 15:52 UTC, joshuajames-smith approved these changes, later dismissed

2022-07-28 10:09 UTC, joshuajames-smith approved these changes

2022-07-28 10:11 UTC, ChasNelson1990 approved these changes

2022-07-28 10:11 UTC, merged

2022-07-28 10:11 UTC, ChrisBaidoo approved these changes