feat: Click to select annotations
gliff-ai/annotate pull request #85
Opened 2021-04-08 08:23 UTC by SilviaZeta

# Description

Add the ability to select paintbrush or spline annotations with a single click on the annotation. When selected, an annotation becomes active and can then be modified or deleted.

For paintbrush annotations you can toggle between draw and select mode with ctrl+a (to try this out, draw multiple annotations, ctrl+a, click on existing annotations and delete, ctrl+a and draw some more..).

closes #84 

# Dependency changes

No

# Testing

No

# Documentation

N/A

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~I have made corresponding changes to the documentation~
- [x] My changes generate no new warnings
- [ ] ~I have added tests that prove my fix is effective or that my feature works~
- [x] New and existing unit tests pass locally with my changes

2021-04-08 08:55 UTC, ChasNelson1990 requested changes
Can we use a different cursor for select mode? Maybe the pointy finger hand?

2021-04-08 08:57 UTC, ChasNelson1990 commented
Also, do we want to enforce the same keyboard shortcut for both paintbrushes and splines just for consistency?

2021-04-09 07:57 UTC, cooper667 approved these changes

2021-04-09 07:57 UTC, cooper667 commented on src/toolboxes/spline/Canvas.tsx
> +    if (Math.abs(crossProduct) > 700) return false;
Maybe this value should be a constant at the top?

2021-04-09 08:07 UTC, ChasNelson1990 commented
Also, one more change to propose, can we make the active paintbrush a standard colour so its clear that you've activated the right one? Or give it a stroke*? We could be the active paintbrush palette:primary? as I think the colour when your painting is palette:secondary?
* if we go for stroke let's make it that pink (palette: secondary?)

2021-04-09 08:15 UTC, SilviaZeta commented
> Also, one more change to propose, can we make the active paintbrush a standard colour so its clear that you've activated the right one? Or give it a stroke*? We could be the active paintbrush palette:primary? as I think the colour when your painting is palette:secondary?
> 
> * if we go for stroke let's make it that pink (palette: secondary?)

Can we open a new issue for this?

2021-04-09 08:16 UTC, SilviaZeta commented on src/toolboxes/paintbrush/Canvas.tsx
> +  private mode: number;
Typescript is happy with number.

2021-04-09 08:17 UTC, cooper667 commented
> Also, one more change to propose, can we make the active paintbrush a standard colour so its clear that you've activated the right one? Or give it a stroke*? We could be the active paintbrush palette:primary? as I think the colour when your painting is palette:secondary?
> 
> * if we go for stroke let's make it that pink (palette: secondary?)

I think this will be solved when we do opacity on the strokes? Solid for selected, 50% opaque for others?

2021-04-09 08:38 UTC, SilviaZeta commented on src/toolboxes/paintbrush/Canvas.tsx
> +  private mode: number;
Typescript is also happy with Mode, so I've changed this as Mode is more specific.

2021-04-09 08:39 UTC, cooper667 commented on src/toolboxes/paintbrush/Canvas.tsx
> +  private mode: number;
👍  thanks

2021-04-09 08:44 UTC, ChasNelson1990 approved these changes

2021-04-09 09:01 UTC, cooper667 approved these changes

2021-04-09 11:01 UTC, merged